# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: PowerShell@2
  name: "DockerHub_Login"
  inputs:
    targetType: 'inline'
    script: 'docker login docker.io -u="$(DOCKER_USERNAME)" -p="$(DOCKER_PASSWORD)"'

- task: PowerShell@2
  name: "Build_Chrome_Node_Image"
  inputs:
    targetType: 'inline'
    script: 'make chrome'

- task: PowerShell@2
  name: "Tag_Image"
  inputs:
    targetType: 'inline'
    script: |
      $tag1 = "mcopjan/selenium4_chrome_en_gb:latest"
      $tag2 = "mcopjan/selenium4_chrome_en_gb:$(ChromeTag)"
      echo "Tagging image with  -> $tag1 and $tag2"
      docker tag selenium/node-chrome:4.0.0-beta-1-20210126 $tag1
      docker tag selenium/node-chrome:4.0.0-beta-1-20210126 $tag2

- task: PowerShell@2
  name: "Push_Docker_Image"
  inputs:
    targetType: 'inline'
    script: |
      docker push mcopjan/selenium4_chrome_en_gb:latest
      docker push mcopjan/selenium4_chrome_en_gb:$(ChromeTag)


- task: PowerShell@2
  name: "DockerHub_Logout"
  inputs:
    targetType: 'inline'
    script: 'docker logout docker.io'