# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'make chrome_debug'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      docker tag selenium/node-chrome-debug:3.141.59-zinc mcopjan/selenium_chromenode_debug_custom:3.141.59-zinc-bg

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub_Mcopjan'
    repository: 'mcopjan/selenium_chromenode_debug_custom'
    command: 'push'
    tags: '3.141.59-zinc-bg'