# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: PowerShell@2
  name: "DockerHub_Login"
  inputs:
    targetType: 'inline'
    script: 'docker login docker.io -u="$(DOCKER_USERNAME)" -p="$(DOCKER_PASSWORD)"'

- task: PowerShell@2
  name: "Build_Chrome_Node_Image"
  inputs:
    targetType: 'inline'
    script: 'make chrome_debug'




- task: PowerShell@2
  name: "DockerHub_Logout"
  inputs:
    targetType: 'inline'
    script: 'docker logout docker.io'