# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@2
  name: "LoginToDockerHub"
  inputs:
    containerRegistry: 'DockerHub_Mcopjan'
    command: 'login'
- task: PowerShell@2
  name: "Build_Chrome_Node_Image"
  inputs:
    targetType: 'inline'
    script: 'make chrome_debug'

- task: PowerShell@2
  name: "Tag_Image"
  inputs:
    targetType: 'inline'
    script: |
      $tag = "mcopjan/selenium_chromenode_debug_custom:3.141.59-zinc-bg"
      echo "Tagging image -> $tag"
      docker tag selenium/node-chrome-debug:3.141.59-zinc $tag
- task: PowerShell@2
  name: "Push_Image"
  inputs:
    targetType: 'inline'
    script: |
      docker push mcopjan/selenium_chromenode_debug_custom:3.141.59-zinc-bg

- task: Docker@2
  name: "LogoutFromDockerHub"
  inputs:
    containerRegistry: 'DockerHub_Mcopjan'
    command: 'logout'